import { Router } from 'express';
import { getUsers, getUser } from '../controllers/user.controller.js';
import { authorise } from "../middlewares/auth.middleware.js";
const userRouter = Router();
userRouter.get('/',getUsers);
userRouter.get('/:id',authorise,getUser);
userRouter.post('/',(req,res)=>{res.send({'title':'CREATE a user'})});
userRouter.post('/:id',(req,res)=>{res.send({'title':'UPDATE a user'})});
userRouter.delete('/:id',(req,res)=>{res.send({'title':'DELETE a user'})});
export default userRouter;